/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_dynamodb_all_tables_region": "us-east-1",
    "aws_dynamodb_table_schemas": [
        {
            "tableName": "blogwebsiteDB-dev",
            "region": "us-east-1"
        }
    ],
    "aws_user_files_s3_bucket": "blogwebsite803d5b017d9949fcb18e95d79b166ad1151731-dev",
    "aws_user_files_s3_bucket_region": "us-east-1",
    "aws_cloud_logic_custom": [
        {
            "name": "blogapi",
            "endpoint": "https://k9tkh2vr1e.execute-api.us-east-1.amazonaws.com/dev",
            "region": "us-east-1"
        }
    ],
    "aws_cognito_identity_pool_id": "us-east-1:6c36569d-c5a7-4721-acab-b8bce0f6cb6d",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_7RemMcWlM",
    "aws_user_pools_web_client_id": "63561b8136sn9bn8qvvk04hj8c",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ]
};


export default awsmobile;
